# -*- shell-script -*-

# Where the dotfiles are located
export DOTFILES_HOME=${HOME}/Library/dotfiles
export EMAIL_ADDRESS="jon.monette@gmail.com"

autoload -Uz compinit
compinit

# Source global zsh config files, if they exist
[ -f /etc/zshenv ] && source /etc/zshenv
[ -f /etc/zshrc ] && source /etc/zshrc

# source the zsh config files, if they exist
[ -f ${DOTFILES_HOME}/zsh/zsh-aliases.zsh ] && source ${DOTFILES_HOME}/zsh/zsh-aliases.zsh
[ -f ${DOTFILES_HOME}/zsh/zsh-cloudflare.zsh ] && source ${DOTFILES_HOME}/zsh/zsh-cloudflare.zsh
[ -f ${DOTFILES_HOME}/zsh/zsh-functions.zsh ] && source ${DOTFILES_HOME}/zsh/zsh-functions.zsh
[ -f ${DOTFILES_HOME}/zsh/zsh-prompt.zsh ] && source ${DOTFILES_HOME}/zsh/zsh-prompt.zsh
[ -f ${DOTFILES_HOME}/zsh/zsh-keybindings.zsh ] && source ${DOTFILES_HOME}/zsh/zsh-keybindings.zsh
[ -f ${DOTFILES_HOME}/zsh/zsh-history.zsh ] && source ${DOTFILES_HOME}/zsh/zsh-history.zsh
[ -f ${DOTFILES_HOME}/zsh/zsh-misc.zsh ] && source ${DOTFILES_HOME}/zsh/zsh-misc.zsh
[ -f ${DOTFILES_HOME}/zsh/zsh-completions.zsh ] && source ${DOTFILES_HOME}/zsh/zsh-completions.zsh
[ -f ${DOTFILES_HOME}/zsh/zsh-homebrew.zsh ] && source ${DOTFILES_HOME}/zsh/zsh-homebrew.zsh
[ -f ${DOTFILES_HOME}/zsh/zsh-path.zsh ] && source ${DOTFILES_HOME}/zsh/zsh-path.zsh
[ -f ${DOTFILES_HOME}/zsh/zsh-less.zsh ] && source ${DOTFILES_HOME}/zsh/zsh-less.zsh
[ -f ${DOTFILES_HOME}/zsh/zsh-openai.zsh ] && source ${DOTFILES_HOME}/zsh/zsh-openai.zsh

# source the ssh aliases file, if they exist
[ -f ${DOTFILES_HOME}/ssh/ssh.aliases ] && source ${DOTFILES_HOME}/ssh/ssh.aliases

# source the shell configurations for git, if it exists
[ -f ${DOTFILES_HOME}/git/git-shell.cf ] && source ${DOTFILES_HOME}/git/git-shell.cf

# source the shell configurations for maven, if it exists
[ -f ${DOTFILES_HOME}/maven/mvn-shell.cf ] && source ${DOTFILES_HOME}/maven/mvn-shell.cf

# source user settings
[ -f ${HOME}/.zshrc_user ] && source ${HOME}/.zshrc_user

# LOVE DEM EMACS
export EDITOR=emacs

export HOSTFILE=$HOME/.ssh/known_hosts
